### ISSUE TITLE
@GenerateMocks doesn't generate any code

### ISSUE THREAD

**Issue by ova2** [dart-lang/mockito#288]
I have tried to follow your example with `@GenerateMocks`
https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md

```dart
// http_server_test.dart:
import 'package:mockito/annotations.dart';
import 'package:test/test.dart';
import 'http_server.dart';
import 'http_server_test.mocks.dart';

@GenerateMocks([HttpServer])
void main() {
  test('test', () {
    var httpServer = MockHttpServer();
    // We want to stub the `start` method.
  });
}
```

but no code is generated by `@GenerateMocks` in my test class. I execute `build_runner` with

```sh
flutter.bat packages pub run build_runner build --delete-conflicting-outputs
```

My dependencies include

```xml
 mockito: 4.1.2
 build_runner: 1.10.2
```

My `build.yaml` looks like

```xml
targets:
  $default:
    sources:
      include:
        - i18n/**
        - lib/**
        - $package$
    builders:
      json_serializable:
        options:
          explicit_to_json: true
builders:
  mockBuilder:
    import: "package:mockito/src/builder.dart"
    builder_factories: ["buildMocks"]
    build_extensions: {".dart": [".mocks.dart"]}
    build_to: source
```

I also tried `- test/**` as target too. No success. I also tried without `mockBuilder` and with `mockBuilder` below `builders` section. The same.

What I'm doing wrong? Do you have a running example? Thanks!

**Comment by srawlins** [comment]
Sorry about that. I definitely need to update the documentation. I think maybe what may the resolution is to use the `mockito|mockBuilder` builder in your build.yaml file. (I don't even mention this file in the instructions ☹️  ):

```yaml
targets:
  $default:
    builders:
      mockito|mockBuilder:
        enabled: true
```

The command I've used is similar to yours: `pub run build_runner build`.

When running this in a package with a file `test/foo_test.dart` with a @GenerateMocks annotations, I get a new file in the source tree, at `test/foo_test.mocks.dart`.

**Comment by ova2** [comment]
@srawlins Thanks for a prompt answer! This works like a charm now. I have just one little problem - we only can run `build_runner` from the project root folder. By this reason, I have added `- test/**` to the `build.yaml` as follows:

```yaml
targets:
  $default:
    sources:
      include:
        - i18n/**
        - lib/**
        - test/**
        - $package$
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      mockito|mockBuilder:
        enabled: true
```

The mock file will be generated, but I have some warning in the console:

![image](https://user-images.githubusercontent.com/767334/95899609-1d6c7c00-0d91-11eb-8f50-e3b32aa21496.png)

Do you know how to add target folder `test/**` for `mockito|mockBuilder` only? Thanks again.
