### ISSUE TITLE
Colission mockito null-safety with protobuf null-safety

### ISSUE THREAD

**Issue by remonh87** [dart-lang/mockito#312]
Add the following dependencies to pubspec.yaml

```yaml
dependencies:
  protobuf: ^2.0.0-nullsafety

dev_dependencies:
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety
```

```
Because mockito >=4.1.2 depends on code_builder ^3.4.0 which depends on built_value ^7.0.0, mockito >=4.1.2 requires built_value ^7.0.0.
And because built_value >=5.5.5 <8.0.0-nullsafety.0 depends on fixnum ^0.10.0, mockito >=4.1.2 requires fixnum ^0.10.0.
And because protobuf 2.0.0-nullsafety.0 depends on fixnum ^1.0.0-nullsafety.0 and no versions of protobuf match >=2.0.0-nullsafety <2.0.0-nullsafety.0 or >2.0.0-nullsafety.0 <3.0.0, mockito >=4.1.2 is incompatible with protobuf ^2.0.0-nullsafety.
So, because flutter_reactive_ble depends on both protobuf ^2.0.0-nullsafety and mockito ^5.0.0-nullsafety, version solving failed.
```

Looks like mockito is using outdated version of fixnum for null-safety.
