### ISSUE TITLE
Using the "records" dart language feature

### ISSUE THREAD

**Issue by buehler** [dart-lang/mockito#607]
Dear Mockito-Team

When using the new experimental dart feature ("records"), the mock builder explodes during build:

```
line 210, column 337 of .: This requires the 'records' language feature to be enabled.
    ╷
210 │ class MockBookService extends _i1.Mock implements _i31.BookService {@override _i8.Future<(Book, Chapter)> getFavoriteChapters() => (super.noSuchMethod(Invocation.method(#getFavoriteChapters, [], ), returnValue: _i8.Future<(Book, Chapter)>.value(null), returnValueForMissingStub: _i8.Future<(Book, Chapter)>.value(null), ) as _i8.Future<(Book, Chapter)>);
    │
package:dart_style/src/dart_formatter.dart 144:7  DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 72:12  DartFormatter.format
package:mockito/src/builder.dart 128:48           MockBuilder.build
```

This happens despite the fact that the experiment should be enabled:
`flutter pub run build_runner build -d --enable-experiment records -v`

The build yaml config:
```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          sql:
            dialect: sqlite
            options:
              modules:
                - fts5
      # Disable mockito's builder to run it after other code is generated.
      mockito|mockBuilder:
        enabled: false
        options:
          records: true
  mockito:
    dependencies: [ "$default" ]
    auto_apply_builders: false
    builders:
      mockito|mockBuilder:
        enabled: true
        options:
          records: true

```

**Comment by buehler** [comment]
Yeah sure:
pubspec.yaml
```yaml
environment:
  sdk: '>=2.19.0 <3.0.0'
```

And the reproduction case, is pretty much any service that uses records :-)

In our case we had:

```yaml
analyzer:
  enable-experiment:
    - records
```

And a service:

```dart
class FooService {
  // some internal dependency injection

  Future<List<(String, bool)>> getMyStuff() async {
    /* ... */
  }
}
```

And for mock generation:
```dart
@GenerateNiceMocks([
  MockSpec<FooService>(onMissingStub: OnMissingStub.returnDefault),
// @stacked-mock-spec
])
void registerMocks(){
  // ...
}
```

This scenario resulted in the error described.
