### ISSUE TITLE
I configured build.yaml as this repo, but it's not working as I expected

### ISSUE THREAD

**Issue by HeronKyaw** [dart-lang/mockito#693]
I created a `build.yaml` as [this](https://github.com/dart-lang/mockito/blob/master/build.yaml) but it's not creating a mock directory.
Here's my code:
```
targets:
  $default:
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
        options:
          build_extensions:
            '^test/{{}}.dart' : 'test/mocks/{{}}.mocks.dart'

builders:
  mockBuilder:
    import: "package:mockito/src/builder.dart"
    builder_factories: ["buildMocks"]
    build_extensions: {".dart": [".mocks.dart"]}
    build_to: source
    auto_apply: dependents
    defaults:
      generate_for: ['test/**']
```

here's my pubspec.yaml -
```
dev_dependencies:
    mockito: 5.4.2
    build_runner: ^2.4.6
```

Before generating -
```
└── test
    └── example_bloc_test.dart
```

After generating - 
```
└── test
    ├── example_bloc_test.dart
    └── example_bloc_test.mocks.dart
```

What it is supposed to be -
```
└── test
    ├── example_bloc_test.dart
    └── mock
        └── example_bloc_test.mocks.dart
```
